version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoinits
    - nonamedreturns
    - wsl
    - lll
    - godoclint # False positive with doc.go pattern
    - errchkjson # Examples and test code don't need strict JSON marshaling checks
    - ireturn # Provider interface requires returning interfaces
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    funlen:
      lines: 60
      statements: 60
    gocyclo:
      min-complexity: 15
    cyclop:
      max-complexity: 15
    mnd:
      ignored-numbers:
        - "10"
        - "100"
        - "1000"
        - "2"
        - "60"
        - "60.0"
        - "64"
        - "500"
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    varnamelen:
      max-distance: 5
      min-name-length: 3
      check-receiver: false
      check-return: false
      ignore-type-assert-ok: false
      ignore-map-index-ok: false
      ignore-chan-recv-ok: false
      ignore-decls:
        - wg sync.WaitGroup
        - wg *sync.WaitGroup
        - mu sync.Mutex
        - ok bool
      ignore-names:
        - i
        - w
        - r
        - b
        - c
        - m
        - n
        - tt
        - rw
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples/
      - cmd/
      - generated\.go$
    rules:
      - linters:
          - funlen
          - dupl
          - gocognit
          - gocyclo
          - cyclop
          - errcheck
          - testableexamples
        path: _test\.go
      - linters:
          - cyclop
          - gocyclo
        source: "func \\(c \\*rateLimitedHTTPClient\\) Do"
      - linters:
          - funlen
        text: "NewWithConfig"
      - linters:
          - forbidigo
          - gocyclo
          - cyclop
          - goconst
          - funlen
          - gocognit
          - nestif
          - gocritic
          - maintidx
        path: examples/
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples/
      - cmd/
      - generated\.go$
