# Markdown linting configuration
# Technical documentation requires longer lines for URLs, code examples, and technical content

# Disable line length rule - technical documentation often needs longer lines
MD013: false

# Allow inline HTML for badges, special formatting
MD033: false

# Disable table column alignment - too strict for configuration tables
MD060: false
