// Package webhook provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package webhook

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AcceptHeader.
const (
	AcceptHeaderApplicationexternalDnsWebhookJsonVersion1 AcceptHeader = "application/external.dns.webhook+json;version=1"
)

// Defines values for ContentTypeHeader.
const (
	ContentTypeHeaderApplicationexternalDnsWebhookJsonVersion1 ContentTypeHeader = "application/external.dns.webhook+json;version=1"
)

// Defines values for NegotiateParamsAccept.
const (
	NegotiateParamsAcceptApplicationexternalDnsWebhookJsonVersion1 NegotiateParamsAccept = "application/external.dns.webhook+json;version=1"
)

// Defines values for AdjustRecordsParamsAccept.
const (
	AdjustRecordsParamsAcceptApplicationexternalDnsWebhookJsonVersion1 AdjustRecordsParamsAccept = "application/external.dns.webhook+json;version=1"
)

// Defines values for AdjustRecordsParamsContentType.
const (
	AdjustRecordsParamsContentTypeApplicationexternalDnsWebhookJsonVersion1 AdjustRecordsParamsContentType = "application/external.dns.webhook+json;version=1"
)

// Defines values for GetRecordsParamsAccept.
const (
	GetRecordsParamsAcceptApplicationexternalDnsWebhookJsonVersion1 GetRecordsParamsAccept = "application/external.dns.webhook+json;version=1"
)

// Defines values for SetRecordsParamsAccept.
const (
	SetRecordsParamsAcceptApplicationexternalDnsWebhookJsonVersion1 SetRecordsParamsAccept = "application/external.dns.webhook+json;version=1"
)

// Defines values for SetRecordsParamsContentType.
const (
	SetRecordsParamsContentTypeApplicationexternalDnsWebhookJsonVersion1 SetRecordsParamsContentType = "application/external.dns.webhook+json;version=1"
)

// Changes This is the list of changes send by `external-dns` that need to
// be applied.  There are four lists of endpoints.  The `create`
// and `delete` lists are lists of records to create and delete
// respectively.  The `updateOld` and `updateNew` lists are paired.
// For each entry there's the old version of the record and a new
// version of the record.
type Changes struct {
	// Create This is a list of DNS records.
	Create *Endpoints `json:"create,omitempty"`

	// Delete This is a list of DNS records.
	Delete *Endpoints `json:"delete,omitempty"`

	// UpdateNew This is a list of DNS records.
	UpdateNew *Endpoints `json:"updateNew,omitempty"`

	// UpdateOld This is a list of DNS records.
	UpdateOld *Endpoints `json:"updateOld,omitempty"`
}

// Endpoint This is a DNS record.
type Endpoint struct {
	DnsName          *string                     `json:"dnsName,omitempty"`
	Labels           *map[string]string          `json:"labels,omitempty"`
	ProviderSpecific *[]ProviderSpecificProperty `json:"providerSpecific,omitempty"`
	RecordTTL        *int64                      `json:"recordTTL,omitempty"`
	RecordType       *string                     `json:"recordType,omitempty"`
	SetIdentifier    *string                     `json:"setIdentifier,omitempty"`

	// Targets This is the list of targets that this DNS record points to.
	// So for an A record it will be a list of IP addresses.
	Targets *Targets `json:"targets,omitempty"`
}

// Endpoints This is a list of DNS records.
type Endpoints = []Endpoint

// Filters external-dns will only create DNS records for host names (specified in ingress objects and services with the external-dns annotation) related to zones that match filters. They can set in external-dns deployment manifest.
type Filters struct {
	Filters *[]string `json:"filters,omitempty"`
}

// ProviderSpecificProperty Allows provider to pass property specific to their implementation.
type ProviderSpecificProperty struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// Targets This is the list of targets that this DNS record points to.
// So for an A record it will be a list of IP addresses.
type Targets = []string

// AcceptHeader defines model for AcceptHeader.
type AcceptHeader string

// ContentTypeHeader defines model for ContentTypeHeader.
type ContentTypeHeader string

// NegotiateParams defines parameters for Negotiate.
type NegotiateParams struct {
	// Accept Must be application/external.dns.webhook+json;version=1
	Accept NegotiateParamsAccept `json:"Accept"`
}

// NegotiateParamsAccept defines parameters for Negotiate.
type NegotiateParamsAccept string

// AdjustRecordsParams defines parameters for AdjustRecords.
type AdjustRecordsParams struct {
	// Accept Must be application/external.dns.webhook+json;version=1
	Accept AdjustRecordsParamsAccept `json:"Accept"`

	// ContentType Must be application/external.dns.webhook+json;version=1
	ContentType AdjustRecordsParamsContentType `json:"Content-Type"`
}

// AdjustRecordsParamsAccept defines parameters for AdjustRecords.
type AdjustRecordsParamsAccept string

// AdjustRecordsParamsContentType defines parameters for AdjustRecords.
type AdjustRecordsParamsContentType string

// GetRecordsParams defines parameters for GetRecords.
type GetRecordsParams struct {
	// Accept Must be application/external.dns.webhook+json;version=1
	Accept GetRecordsParamsAccept `json:"Accept"`
}

// GetRecordsParamsAccept defines parameters for GetRecords.
type GetRecordsParamsAccept string

// SetRecordsParams defines parameters for SetRecords.
type SetRecordsParams struct {
	// Accept Must be application/external.dns.webhook+json;version=1
	Accept SetRecordsParamsAccept `json:"Accept"`

	// ContentType Must be application/external.dns.webhook+json;version=1
	ContentType SetRecordsParamsContentType `json:"Content-Type"`
}

// SetRecordsParamsAccept defines parameters for SetRecords.
type SetRecordsParamsAccept string

// SetRecordsParamsContentType defines parameters for SetRecords.
type SetRecordsParamsContentType string

// AdjustRecordsApplicationExternalDNSWebhookPlusJSONVersion1RequestBody defines body for AdjustRecords for application/external.dns.webhook+json;version=1 ContentType.
type AdjustRecordsApplicationExternalDNSWebhookPlusJSONVersion1RequestBody = Endpoints

// SetRecordsApplicationExternalDNSWebhookPlusJSONVersion1RequestBody defines body for SetRecords for application/external.dns.webhook+json;version=1 ContentType.
type SetRecordsApplicationExternalDNSWebhookPlusJSONVersion1RequestBody = Changes

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Initialisation and negotiates headers and returns domain filter.
	// (GET /)
	Negotiate(ctx echo.Context, params NegotiateParams) error
	// Executes the AdjustEndpoints method.
	// (POST /adjustendpoints)
	AdjustRecords(ctx echo.Context, params AdjustRecordsParams) error
	// Returns the current records.
	// (GET /records)
	GetRecords(ctx echo.Context, params GetRecordsParams) error
	// Applies the changes.
	// (POST /records)
	SetRecords(ctx echo.Context, params SetRecordsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Negotiate converts echo context to params.
func (w *ServerInterfaceWrapper) Negotiate(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params NegotiateParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept NegotiateParamsAccept
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Accept, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Accept: %s", err))
		}

		params.Accept = Accept
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Accept is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Negotiate(ctx, params)
	return err
}

// AdjustRecords converts echo context to params.
func (w *ServerInterfaceWrapper) AdjustRecords(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AdjustRecordsParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept AdjustRecordsParamsAccept
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Accept, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Accept: %s", err))
		}

		params.Accept = Accept
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Accept is required, but not found"))
	}
	// ------------- Required header parameter "Content-Type" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Content-Type")]; found {
		var ContentType AdjustRecordsParamsContentType
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Content-Type, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Content-Type", valueList[0], &ContentType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Content-Type: %s", err))
		}

		params.ContentType = ContentType
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Content-Type is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdjustRecords(ctx, params)
	return err
}

// GetRecords converts echo context to params.
func (w *ServerInterfaceWrapper) GetRecords(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRecordsParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept GetRecordsParamsAccept
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Accept, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Accept: %s", err))
		}

		params.Accept = Accept
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Accept is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRecords(ctx, params)
	return err
}

// SetRecords converts echo context to params.
func (w *ServerInterfaceWrapper) SetRecords(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SetRecordsParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept SetRecordsParamsAccept
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Accept, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Accept: %s", err))
		}

		params.Accept = Accept
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Accept is required, but not found"))
	}
	// ------------- Required header parameter "Content-Type" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Content-Type")]; found {
		var ContentType SetRecordsParamsContentType
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Content-Type, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Content-Type", valueList[0], &ContentType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Content-Type: %s", err))
		}

		params.ContentType = ContentType
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Content-Type is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetRecords(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/", wrapper.Negotiate)
	router.POST(baseURL+"/adjustendpoints", wrapper.AdjustRecords)
	router.GET(baseURL+"/records", wrapper.GetRecords)
	router.POST(baseURL+"/records", wrapper.SetRecords)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xZbW/bOBL+KwPeAXeHc2QnfUGgw33wZtNusG1aNAH2Q2wgtDS22EqkSo7iuoH/+4Kk",
	"ZEm2/LbpBov9EkAm5+Fw5pk35pFFKsuVREmGhY8s55pnSKjd1zCKMKdfkMeo7XeMJtIiJ6EkC9n7whBM",
	"EHiepyLi9tc+fiPUkqdBLE0wx0mi1Jf/fjZK/u8BtRFK/v+U9Ziw4omH7THJM2RheRjrMY1fC6ExZiHp",
	"AnvMRAlm3J6PsshYeMeOPXHcY7TI7SGGtJAztlz22IWShJJuFzk+0w3LE0/skc91z2WF6xwaJVzO0Gze",
	"9DYRBoQBShBSYQjUFMrNYFDGMFnAfaXCSSzNPVDCCSRiDKRGsrISxgHAbYIagWuEqSq0AzQWEWWcKyHJ",
	"+D1wH2nkhPcjyWUM9zGmSHhf7rfiK0mNkdKxAVLgZcBKeIGR1GhyjEg8YLqooIs85oQf0vjebS2/r3He",
	"xM+5dUAwkm+UBuRRAihJL6wZNP7Lm0OlMZQmtprYn7w2DpeDxPlIdm4IRpL1GH7jWZ6iM79TnYV3jyyW",
	"5tqzYqpUUO4JIpU5Yljp29t3LHw9WH16xw7Zctxj/uI7gJSesTXJi+vh+0u2HC97LNcqR03CM6HS6pH9",
	"U+OUhewf/Top9Ev29Fe+Y8v6/CNEVvb/A1If0vgIqeUqCtTkM0Zkcarl7czn8PP1zTbHPcFb69ZeQT3W",
	"B3S4bi2OeyzlE0wdAo9jYZXn6ccWcguuC6JxIbsjZBOuWZe1cq0eRIz6JsdITEXUQr97rPKZP+aBpwVW",
	"YOMeE4SZ2eeu9RPKmywa6nCtuftuGLihhrX1VOmMEwuZkPT6ZX1lIQlnqBvC7vemiXw0dBjJIF3FKElM",
	"hS8JtczDaZcAcT1D2nvjattOeppd/Kzycs1Ts0bUJ+eVg3y3iqUOX01FWjUP7Ws0awfMRZqCkumiSuaN",
	"K8FUaUiUIbAsM/Bv4ymCMQgJQs40GgPedMalYIP6QURoYSlx6bd1GJdSkauh/wGNKSdXseC7kmh8Ecs4",
	"RQmUqge2fCwg4hIMkj2zhRZjnqpFhtKKSTFFQxvZYmWEO7bmgVaQb2bihvVqn7Yxmk7qzh/+pE2atjx1",
	"SNSvYnLDmcM0VXMDlYA1Z86N+8FJQOmzyK5QgkKDsLpZszlPbJhse0ZZt5HsSp5dFy5RmjstYFcruGGK",
	"Rkzv75PKzZ5LZDfUdAYf1kAqGMkb5cjNJQyrZUE+GGz7tAK8+gg8ji3PcSPC2WlwFrwIXLKz3GsRqpMb",
	"YXh6AB+WtmedKtcPKEk8cqWy0KntY4lyE/b7M0FJMbEE638pJqglEpoTI2am34wR3yA0rXZVOd+0wtPZ",
	"qWxlG70h67FURChNkxnDnEcJwlkwYL01tebzecDdsrVCv5Q1/XdXF5fXN5cnZ8EgSChL3a0FOaNcNlX4",
	"rVThBvWD69fLbs6m/EFw+ioYWFGVo+S5YCF7EQycGjmnxBm7b//MsKO7uJKCBE+FcbR36UriTJHghAb8",
	"gOCzmEYqtE0wKuNCjqTPBd79lv8O4CpmIbuuAJwK9bx215226y391jxn871tnJU1ltX8bDCo3I++Uzp2",
	"/mjyrpUGWxls2Rx1dhWaCsCxcz0O6/jzFjN16K3ykq0MPoSWPfbKX6+NU9nSOmfKReqGAZcTTJFlXC+e",
	"4MOyolg+E585O4gS6ruDYmN7UJ/HnwtDrRYgV6aDTEO30TQmDGPrk/1cXXnCDcag7K/KIJjCD2VgB5ou",
	"MnnMTx7tiYTq7d2/OXN7Fn4t0NBPKl78QAK2mqFWrtzohk43u6FGDahz7thqexh3m/NIB3u3T9ukoDFL",
	"O4+1HwqWf2rYHmG1ZzaaZ6qvInP3vuDIV0bslvjeEJKK2oKtUL/8hlFB6D3jZS8rnSBDSlTcDGc/nZZh",
	"XEbk1lLwFsnBRoXWtn1c9btaZW6hlbrqdGLXsq7QfYs/KG7HfxVGPXccfvTWjluB2JxFTBFFaMy0SNPF",
	"Lpq9caXD9cEechviJuU+lTWjgxpNqlks27m5oaGzOtyU/FqrDC1WHVsdbvBvWRq2vMQdTc7l4b1M9fJ6",
	"bDVoPLJC9xvrSB72yAq73lhHcs8jK+x/Yx3JnY+sAIc9sjpVul5ZYccj674S+XIzXi5KEx9cS1oCu+vI",
	"0LmpDGov1l033IOTnTp8TK1HtF2BQqd+boRfV1NX4x0iaA1EYb+fqoiniTIUnp+fn7swKg9eP6CubRa/",
	"bE5Xza2d0+t/Xqy1rjait4GRghkSlCnLrKfAGrNKanvAvLm2YJS2XI6XvwcAAP//QJ03rcwaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
