// Package webhook provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package webhook

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Changes This is the list of changes send by `external-dns` that need to
// be applied.  There are four lists of endpoints.  The `create`
// and `delete` lists are lists of records to create and delete
// respectively.  The `updateOld` and `updateNew` lists are paired.
// For each entry there's the old version of the record and a new
// version of the record.
type Changes struct {
	// Create This is a list of DNS records.
	Create *Endpoints `json:"create,omitempty"`

	// Delete This is a list of DNS records.
	Delete *Endpoints `json:"delete,omitempty"`

	// UpdateNew This is a list of DNS records.
	UpdateNew *Endpoints `json:"updateNew,omitempty"`

	// UpdateOld This is a list of DNS records.
	UpdateOld *Endpoints `json:"updateOld,omitempty"`
}

// Endpoint This is a DNS record.
type Endpoint struct {
	DnsName          *string                     `json:"dnsName,omitempty"`
	Labels           *map[string]string          `json:"labels,omitempty"`
	ProviderSpecific *[]ProviderSpecificProperty `json:"providerSpecific,omitempty"`
	RecordTTL        *int64                      `json:"recordTTL,omitempty"`
	RecordType       *string                     `json:"recordType,omitempty"`
	SetIdentifier    *string                     `json:"setIdentifier,omitempty"`

	// Targets This is the list of targets that this DNS record points to.
	// So for an A record it will be a list of IP addresses.
	Targets *Targets `json:"targets,omitempty"`
}

// Endpoints This is a list of DNS records.
type Endpoints = []Endpoint

// Filters external-dns will only create DNS records for host names (specified in ingress objects and services with the external-dns annotation) related to zones that match filters. They can set in external-dns deployment manifest.
type Filters struct {
	Filters *[]string `json:"filters,omitempty"`
}

// ProviderSpecificProperty Allows provider to pass property specific to their implementation.
type ProviderSpecificProperty struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// Targets This is the list of targets that this DNS record points to.
// So for an A record it will be a list of IP addresses.
type Targets = []string

// AcceptHeader defines model for AcceptHeader.
type AcceptHeader = string

// ContentTypeHeader defines model for ContentTypeHeader.
type ContentTypeHeader = string

// NegotiateParams defines parameters for Negotiate.
type NegotiateParams struct {
	// Accept Should be application/external.dns.webhook+json;version=1
	Accept *AcceptHeader `json:"Accept,omitempty"`
}

// AdjustRecordsParams defines parameters for AdjustRecords.
type AdjustRecordsParams struct {
	// Accept Should be application/external.dns.webhook+json;version=1
	Accept *AcceptHeader `json:"Accept,omitempty"`

	// ContentType Should be application/external.dns.webhook+json;version=1
	ContentType *ContentTypeHeader `json:"Content-Type,omitempty"`
}

// GetRecordsParams defines parameters for GetRecords.
type GetRecordsParams struct {
	// Accept Should be application/external.dns.webhook+json;version=1
	Accept *AcceptHeader `json:"Accept,omitempty"`
}

// SetRecordsParams defines parameters for SetRecords.
type SetRecordsParams struct {
	// Accept Should be application/external.dns.webhook+json;version=1
	Accept *AcceptHeader `json:"Accept,omitempty"`

	// ContentType Should be application/external.dns.webhook+json;version=1
	ContentType *ContentTypeHeader `json:"Content-Type,omitempty"`
}

// AdjustRecordsApplicationExternalDNSWebhookPlusJSONVersion1RequestBody defines body for AdjustRecords for application/external.dns.webhook+json;version=1 ContentType.
type AdjustRecordsApplicationExternalDNSWebhookPlusJSONVersion1RequestBody = Endpoints

// SetRecordsApplicationExternalDNSWebhookPlusJSONVersion1RequestBody defines body for SetRecords for application/external.dns.webhook+json;version=1 ContentType.
type SetRecordsApplicationExternalDNSWebhookPlusJSONVersion1RequestBody = Changes

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Initialisation and negotiates headers and returns domain filter.
	// (GET /)
	Negotiate(w http.ResponseWriter, r *http.Request, params NegotiateParams)
	// Executes the AdjustEndpoints method.
	// (POST /adjustendpoints)
	AdjustRecords(w http.ResponseWriter, r *http.Request, params AdjustRecordsParams)
	// Returns the current records.
	// (GET /records)
	GetRecords(w http.ResponseWriter, r *http.Request, params GetRecordsParams)
	// Applies the changes.
	// (POST /records)
	SetRecords(w http.ResponseWriter, r *http.Request, params SetRecordsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Initialisation and negotiates headers and returns domain filter.
// (GET /)
func (_ Unimplemented) Negotiate(w http.ResponseWriter, r *http.Request, params NegotiateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Executes the AdjustEndpoints method.
// (POST /adjustendpoints)
func (_ Unimplemented) AdjustRecords(w http.ResponseWriter, r *http.Request, params AdjustRecordsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Returns the current records.
// (GET /records)
func (_ Unimplemented) GetRecords(w http.ResponseWriter, r *http.Request, params GetRecordsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Applies the changes.
// (POST /records)
func (_ Unimplemented) SetRecords(w http.ResponseWriter, r *http.Request, params SetRecordsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Negotiate operation middleware
func (siw *ServerInterfaceWrapper) Negotiate(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params NegotiateParams

	headers := r.Header

	// ------------- Optional header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept AcceptHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Negotiate(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdjustRecords operation middleware
func (siw *ServerInterfaceWrapper) AdjustRecords(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AdjustRecordsParams

	headers := r.Header

	// ------------- Optional header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept AcceptHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	// ------------- Optional header parameter "Content-Type" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Content-Type")]; found {
		var ContentType ContentTypeHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Content-Type", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Content-Type", valueList[0], &ContentType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Content-Type", Err: err})
			return
		}

		params.ContentType = &ContentType

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdjustRecords(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecords operation middleware
func (siw *ServerInterfaceWrapper) GetRecords(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRecordsParams

	headers := r.Header

	// ------------- Optional header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept AcceptHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecords(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetRecords operation middleware
func (siw *ServerInterfaceWrapper) SetRecords(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SetRecordsParams

	headers := r.Header

	// ------------- Optional header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept AcceptHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	// ------------- Optional header parameter "Content-Type" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Content-Type")]; found {
		var ContentType ContentTypeHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Content-Type", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Content-Type", valueList[0], &ContentType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Content-Type", Err: err})
			return
		}

		params.ContentType = &ContentType

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetRecords(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.Negotiate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/adjustendpoints", wrapper.AdjustRecords)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/records", wrapper.GetRecords)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/records", wrapper.SetRecords)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xZbW/juBH+KwO2QFtUKyd7L1io6Ad3m7sGveYW5wD9sA4QWhxb3KNIlRzF6wv83wuS",
	"kiXZ8kua66LolwAyOQ+HM8+8Mc8sN2VlNGpyLHtmFbe8REIbvqZ5jhX9DblA678FutzKiqTRLGOzwtRK",
	"wAKBV5WSOfe/T/AzodVcpUK7dI2Lwpif//jJGf2nJ7ROGv3na5Yw6QGKCJwwzUtkWXMcS5jLCyy5P5E2",
	"lV9xZKVese02Ye+NJtR0v6nwiynWnPnGH3pSvW27GMyXF1yv0B0qeF9IB9IBFQhKOgKzhGYzONQCFht4",
	"bPV9I7R7BCo4gUYUQGau26uhSAHuC7QI3CIsTW0DoPOIqEVlpCYX98BjbpETPs411wIeBSokfGz2e/Gd",
	"pMXcWOGADEQZ8BJRYK4tugpzkk+oNi10XQlO+KMSj2Fr832H6z5+xaVFkc71d8YC8rwA1GQ33gwWfxfN",
	"YZSAxh9eE/9T1CbgctC4nuvRDelcs4ThZ15WCoP5g+os+/jMhHZ30ZVLY9JmT5qbkiUsSt/f/8Cyb692",
	"n9GxU7Z9SFi8+AkgY1dsT/L93fQfN2z7sE1YZU2FlmRkQqvVM/utxSXL2G8mXQhOGvZMdr5j2+78F4js",
	"7P8fSP2oxAuktkkbBWbxCXPyOO3yceZz+Ovd7JjjXuGtfWvvoJ67A0ZctxfHCVN8gSogcCGkV56rDwPk",
	"AdwYRO9CfkfGFtyyMWtV1jxJgXZWYS6XMh+gf3xuk1A85omrGluwh4RJwtKdc9f+Cc1NNj11uLU8fPcM",
	"3FPD23ppbMmJZUxq+vbr7spSE67Q9oTD730TxWgYMZJDuhWoSS5lzOSdzNP1mABxu0I6e+N220l6ulP8",
	"bPNyx1O3R9RX55WLfLeLpRFfLaVqS/XwGv3aAWupFBitNm0y710JlsZCYRyBZ5mD37tIERQgNUi9sugc",
	"RNO5kIId2ieZo4elIqTfwWFca0Oh4P4BLCpOoWLBL0aji0Ws5JQX0Kie+vKxgZxrcEj+zAGawEqZTYna",
	"i2m5REcH2WJnhI9szwODID/MxD3rdT4dYvSdNJ4/4kmHNB146pKo38XkgTOnSpm1g1bAm7PiLvwQJKDx",
	"We5XqEBpQXrdvNmCJw5Mdjyj7NtIjyXPsQs3KP2dHjAZ6eAOTNGL6fN9UrM5con8ho7OEMMayKRzPTOB",
	"3FzDtF2WFIPBt087wNsPwIXwPMeDCGfX6dv0qzQkO8+9AaFGuZFl1xfwYesbzaUJ/YDRxPNQKmurfPNJ",
	"VLlsMllJKuqFJ9jk53qBViOhe+Pkyk36MRIbhL7Vblvnu0F4Bjs1fW+vN2QJUzJH7frMmFY8LxDeplcs",
	"2VNrvV6nPCx7K0waWTf54fb9zd3s5s3b9CotqFTh1pKCUW76KvyzUWGG9ik02U0351P+VXr9TXrlRU2F",
	"mleSZeyr9CqoUXEqgrEn/s8KR7qLWy1JciVdoH1IVxpXhiQndBC7+pjFLFJtfYIxJZd6rmMuiO73/A8A",
	"t4Jl7K4FCCp009HH8bTdbZkMpief733jbLyxvOZvr65a92PslF46rPR5N0iDgwy27c8rpwpNCxDYuR+H",
	"XfxFi7ku9HZ5yVeGGELbhH0TrzfEaW3pnbPkUoVhIOQEV5clt5tX+LCpKJ7PxFfBDrKB+iVAsQd/0ISL",
	"T7WjQQtQGTdCpmnY6HoThvP1yX/urrzgDgUY/6txCK6OQxn4gWaMTBHzp4j2SkIlZ/cfjsqRhf+q0dFf",
	"jNj8igQcNEODXHnQDV0fdkO9GtDl3Aev7WXc7c8jI+w9Pm2Tgd4sHTzm7ePnVJaRrXH7Xw3bF1jtCxst",
	"MjVWkXV4XwjkayL2SHwfCGlDQ8FBqN98xrwmjJ6JsjetTlAiFUb0wzlOp00YNxF5tBR8jxRg89pa3z7u",
	"+l1ryrAwSF1dOvFr5Vjofo+/Utw+/K8w6kvH4YdobTEIxP4s4uo8R+eWtVKbUzT7LpSO0AdHyGOIh5T7",
	"qakZI9ToU81j+c4tDA2j1WHW8GuvMgxY9dLqMMP/y9Jw5CXuxeTcXt7LtC+vL60GvUdWGH9jnevLHlnh",
	"1BvrXJ95ZIXzb6xzffKRFeCyR9agytgrK5x4ZD1XIr8+jJf3jYkvriUDgdN1ZBrc1AR1FBuvG+HByU8d",
	"Mab2I9qvQG1VnBvh77upq/cOkQ4GomwyUSbnqjCOsnfv3r0LYdQcvH9AV9s8ftOc7ppbP6d3/3HYa119",
	"RB8DIwMrJGhSlttPgR1mm9TOgEVzHcFobLl92P47AAD//6I9/So6GgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
