// Package health provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package health

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for HealthStatusStatus.
const (
	Error HealthStatusStatus = "error"
	Ok    HealthStatusStatus = "ok"
)

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Message *string             `json:"message,omitempty"`
	Status  *HealthStatusStatus `json:"status,omitempty"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Liveness(ctx echo.Context) error
	// Prometheus metrics
	// (GET /metrics)
	Metrics(ctx echo.Context) error
	// Readiness probe
	// (GET /readyz)
	Readiness(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Liveness converts echo context to params.
func (w *ServerInterfaceWrapper) Liveness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Liveness(ctx)
	return err
}

// Metrics converts echo context to params.
func (w *ServerInterfaceWrapper) Metrics(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Metrics(ctx)
	return err
}

// Readiness converts echo context to params.
func (w *ServerInterfaceWrapper) Readiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Readiness(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/healthz", wrapper.Liveness)
	router.GET(baseURL+"/metrics", wrapper.Metrics)
	router.GET(baseURL+"/readyz", wrapper.Readiness)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUS2/jNhD+K8SkhxZQLCXpAgsBPfSx7Qbdosa6PRRxUNDUSGIicQjOyLUb+L8XpGQn",
	"dpLm0EtPpsbz+h7kAxjqPTl0wlA+AJsWe52OH1F30i5Ey5C+fSCPQSymrx6ZdYPxiBvd+w6hhAWGtTWo",
	"LKs2VW8hA9n6+B9LsK6BXQZ8aIlu6KG8AbqHDDAECnCbPemX4if1u0OEVndoBHYxZF1NsWOFbIL1YslB",
	"OUFQpkVzz0q7Ss0D9SgtDqx6lGANK3SVJ+uEVU1BSYsKN4LB6e68cqx+d/ZHq/7CVUt0P4MMOmvQcULu",
	"dB8X+W7xw/nV+fedHhghgyF0UEIr4rnMc/LomIZgcEahyadqzo+KIigrCfO0c1z2l2nDb+fXkMEaA4+w",
	"LmbFrIg1sbf2Fkq4SqEMvJY2UZuPAvwdzw3Kc24+owzBsbosCvXrz8rWCTo/Kqg7u8a0Rxics66ZLR2k",
	"mUHHHtcVlPDJrtEhM2QQkD1FaHHWZVHEH0NO0KXp2vvOmlSZ33FcYe+2ePoiYA0lnOWPdswnL+ZHRkxq",
	"HyNZnOwcmXk3zn810ZEcLBo78tD3OmyfIFI+0CrKKbrhaNIxHW5jej6Z5012X/CbdUpwI9FtvZaXSJ10",
	"f5vT2Cf3nbYnbD7eoDP18cOnuWroz3hD1LUbp1pySq9okCT6T6TQrW0g16OLG52p3/6YfzhUNXpocOmm",
	"z4fJiN8soaGL2eW72ddL2KmLBOT0sj4Ta+9p3HgKgpXiwRhkroeuO5XiOXlP5NhHRj0C6mr7H8ye6pWQ",
	"0sagFyVB17U1L6nzGXVl/0eeT6uPnr960/NT8hHNB0D/YvlYgCEqD+XNK89sfCr2Jh+T1Zc6iWtXHao6",
	"UK88VemZTZP4q6PXsszzjozuWmIp3xfvC9jd7v4JAAD//+w/hEOhBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
